---
name: DemostraciÃ³n GitHub Actions
on: [push]
jobs:
  Explorar-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ El trabajo fue disparado automÃ¡ticamente por un evento ${{ github.event_name }}."
      - run: echo "ğŸ§ Â¡Este trabajo estÃ¡ corriendo en un servidor ${{ runner.os }} hospedado por GitHub!"
      - run: echo "ğŸ” El nombre de la rama es ${{ github.ref }} y el repositorio es ${{ github.repository }}."
      - name: Descargar el cÃ³digo del repositorio
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ El repositorio ${{ github.repository }} ha sido clonado al ejecutor."
      - run: echo "ğŸ–¥ï¸ El flujo de trabajo estÃ¡ listo para probar el cÃ³digo en el ejecutor."
      - name: Enlistar archivos en el repositorio
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ El estado de este trabajo es ${{ job.status }}."

